version: "3.8"

services:
  go-api:
    build: .
    container_name: go-api
    ports:
      - "8081:8081"
    restart: unless-stopped
  caddy:
    image: caddy:2.10-alpine
    container_name: caddy
    ports:
      - "8082:8082"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped