version: "3.8"

services:
  go-api:
    build: .
    container_name: go-api
    ports:
      - "8081"
    restart: unless-stopped
  caddy:
    image: caddy:2.10-alpine
    container_name: caddy
    ports:
      - "8082:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on: 
      - go-api
      
volumes:
  caddy_data:
  caddy_config: