---
- name: Add Postgresql Compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml
    mode: preserve

- name: Docker-compose up -d
  ansible.builtin.shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu